
gravity_compensation:
  type: panda_controllers/GravityCompensation
  sim: 0
  joints:
    - panda_joint1
    - panda_joint2
    - panda_joint3
    - panda_joint4
    - panda_joint5
    - panda_joint6
    - panda_joint7


force_controller:
  type: panda_controllers/ForceController
  sim: 0
  joints:
    - panda_joint1
    - panda_joint2
    - panda_joint3
    - panda_joint4
    - panda_joint5
    - panda_joint6
    - panda_joint7


hybrid_controller:
  type: panda_controllers/HybridController
  sim: 0
  joints:
    - panda_joint1
    - panda_joint2
    - panda_joint3
    - panda_joint4
    - panda_joint5
    - panda_joint6
    - panda_joint7
