
force_controller:
  type: panda_controllers/ForceController
  sim: 1
  joints:
    - lumi_joint1
    - lumi_joint2
    - lumi_joint3
    - lumi_joint4
    - lumi_joint5
    - lumi_joint6
    - lumi_joint7

hybrid_controller:
  type: panda_controllers/HybridController
  sim: 1
  joints:
    - lumi_joint1
    - lumi_joint2
    - lumi_joint3
    - lumi_joint4
    - lumi_joint5
    - lumi_joint6
    - lumi_joint7
